### ISSUE TITLE
How can i run it?

### ISSUE THREAD

**Issue by ghost** [BobTheBob9/Terraria1.4UltrawidePatcher#2]
It looks like a C# or something i'd run using `csc/msbuild` (internet search, i dont  know that), but it keeps alerting that i dont have `Mono` installed, could you provide a tutorial on how to build and run it?

Thanks!

**Comment by BrianSchnitzer** [comment]
Were you able to run it? I tried compiling it myself (haven't done anything with C# in years) and I also tried running the .exe in the same folder as the Terraria.exe, got nothing.

Edit: Just needed to pass it the path to the Terraria.exe

**Comment by ghost** [comment]
@BrianSchnitzer yes, I downloaded Visual Studio, opened the `.sln` file and compiled.
Then I went to `cmd`, navigated to the .exe folder and entered 
```
<name of exe>.exe "/path/to/Terraria/Terraria.exe" 
```

and it worked, unfortunately, I think after the latest patch it doesnt seem to work, my game crashed before loading the world.
